### DISCUSSION TITLE
Wide dataview

### DISCUSSION THREAD

**Discussion by BindingOx** [GnoxNahte/obsidian-tab-panels#10] [Q&A] [answered]
Does anyone know how to make this compatible with wide dataview? https://efemkay.github.io/obsidian-modular-css-layout/wide-views/

**Comment by GnoxNahte** [comment, marked as answer]
I'm guessing you are seeing this? Note I'm using the sandbox vault

![image](https://github.com/user-attachments/assets/72f973f6-451e-4e11-9dcd-c3114fa758ce)

Not sure if you 
- **do not want** to expand the Dataview block or 
- want to expand the whole tab content when there is a Dataview block. 

I'll just put both solutions here.

## Prevent Dataview from expanding when in tabs
Put this somewhere in a CSS snippet:
```css
@container content-view (width > 50px) {
    :is(.wide-dataview-global, .wide-dataview) .tab-panel-container .cm-preview-code-block:has(> .block-language-dataview),
    :is(.wide-dataview-global, .wide-dataview) .tab-panel-container .cm-preview-code-block:has(> .block-language-dataviewjs) {
        width: initial !important;
        margin-left: initial !important;
    }
    :is(.wide-dataview-global, .wide-dataview) .tab-panel-container div:has(> .block-language-dataview),
    :is(.wide-dataview-global, .wide-dataview) .tab-panel-container div:has(> .block-language-dataviewjs) {
        width: initial !important;
        margin-left: initial !important;
    }
}
```

How it should look like:
![image](https://github.com/user-attachments/assets/a6549447-ec4b-4c23-ab79-5f73c69c4e1b)


## Expand tabs when there's a Dataview block
Put this somewhere in a CSS snippet:
```css
@container content-view (width > 50px) {
    :is(.wide-dataview-global, .wide-dataview) .cm-preview-code-block:has(> .tab-panel-container .block-language-dataview),
    :is(.wide-dataview-global, .wide-dataview) div:has(> .tab-panel-container .block-language-dataview) {
        width: calc(100cqi - 4rem );
        margin-left: calc( max( 100cqi - var(--wide-dv-width-ev), var(--wide-dv-min-left-ev) ) / 2 * -1 ) !important;
    }

    :is(.wide-dataview-global, .wide-dataview) div:has(> .block-language-dataview) {
        width: initial !important;
        margin-left: 0 !important;
    }
}
```

How it should look like:
![image](https://github.com/user-attachments/assets/b790954e-ba03-4dad-812e-81a2077f5d52)
