### ISSUE TITLE
Enhance nested tabs appearance

### ISSUE THREAD

**Issue by dsaperov** [GnoxNahte/obsidian-tab-panels#17]
### Is your feature request related to a problem? Please describe.

Currently if we try to make tabs nested it will look like this:

![image](https://github.com/user-attachments/assets/1d607a7c-4c21-4c67-8682-08c9ee386233)

As for me there are too many "layers". Some of them I think are redundant bacause they take up extra space making the construction more complex than it should be:
![image](https://github.com/user-attachments/assets/653da4fe-42a5-46f5-b977-1f54f1e05f70)

### Describe the solution you'd like
My proposal is to make nested tabs look almost the same as usual (not nested) tabs. Now it is one container (inner tab) inside another (outer tab), and I propose to make it always only one container (because even if we have 2 or more nesting levels the content block we see at a time is always single so we need only one container to see it). I'm not a goot painter so this is my general idea:

![image](https://github.com/user-attachments/assets/453b89fd-bac5-4f35-9000-d3a1311fdce0)

It looks bad but it's just to show the idea (can be formulated as "many nesting levels - only one container").

Just my opinion. No problem, if my idea is bad.

**Comment by GnoxNahte** [comment]
Hey, thanks for the suggestion!

I'm not sure if I should support it as there might be some edge cases

For example, what if there is some text before the tabs, like in the first tabs in the image?
Well, I tried my best to solve it by using CSS and here's the result:
![image](https://github.com/user-attachments/assets/c41821f4-f943-479e-8970-61946d9ed3f1)

CSS:
```css
.tab-panel-container > .content-container:has( > .selected .tab-panel-container:only-child) {
    padding: 0;
    /* Optional */
    /* box-shadow: none; */
}

.tab-panel-container > .content-container > .selected .tab-panel-container:only-child {
    padding: 0;
    border-radius: var(--inner-border-radius);
    border: 0;
}
```

I might add it to the options when I add more styling options. But for now, I won't add it as I think the default behaviour should be the expected behaviour. However, if other users also request it, I'll add it. Well, you can use the CSS snippet if you like the style for now.

Btw unrelated to this issue but I might be busy from 3rd Jan - 3rd Feb (basically the whole of Jan). So I might not be able to solve bugs/features as quickly as I can now (especially if it'll take a lot of work). Still, keep creating issues and I'll solve them whenever I can!
