### ISSUE TITLE
PDF print, insert a page break between certain tabs as they print

### ISSUE THREAD

**Issue by ksdavidc** [GnoxNahte/obsidian-tab-panels#27]
I really like the ability to save as pdf. HOWEVER, it would be really nice if I could insert a page break between certain tabs as they print.

If I put a page break like below: (I tried putting the break inside the 2nd tab as well, with similar result)

````tabs
--section 1

stuff


<div class="page-break" style="page-break-before: always;"></div>

--- section 2

stuff

````

the page looks like this:

<img width="547" alt="Image" src="https://github.com/user-attachments/assets/c645bbf8-e42e-4018-8452-8e653cd4b6f5" />

**Comment by ksdavidc** [comment]
To be clear, not between ALL tabs, just ones I specify.

**Comment by GnoxNahte** [comment]
Would something like this be good? 

![Image](https://github.com/user-attachments/assets/5ff261ec-f507-4cd7-a222-26f2b44e00a9)

I added a way to add custom css classes to the tabs.

For example, something like this:
~~~
```tabs
--- Section 1
Don't page break
--- Section 2 (css-class: pdf-page-break)
Start this tab on a new page
--- Section 3 
Don't page break
```
~~~

Then just add this [css snippet](https://help.obsidian.md/Extending+Obsidian/CSS+snippets):
```css
@media print {
    .content-container > div.pdf-page-break:not(:first-child) {
        break-before: page;
    }
}
```

**Comment by ksdavidc** [comment]
Good? GOOD? That, my good sir or madam, is GENIUS! Thank you for the elegant and prompt solution...

**Comment by GnoxNahte** [comment]
Haha thanks! Glad you liked it:)

**Comment by ksdavidc** [comment]
By the way, and for reference if anyone else lands here, I made one useful related adjustment to the pdf css that prevents page breaks within the individual tabs as well, as well as some cosmetic changes involving hovers:

```css

/* prevents page breaks within a tab */
.tab-panel-container .content-container div {
    break-inside: avoid-page;
}


/* shows me which tabs have page break before */
.tab-panel-container .tab-container li.tab.pdf-page-break p::before {
content: "| ";
}


/* on my theme this looks better */
.tab-panel-container {
background-color:var(--background-primary);
}



/* hover effect on outer container */
.tab-panel-container:hover {
background-color:var(--background-primary-alt);
}



/* Start section: hover on tab
adds a hover effect, since in my theme the tabs looked a little blah 
*/

/* default tab background */
.tab-panel-container .tab {
background-color:var(--background-primary-alt); // have to create contrast
}

/* default selected is brighter than default */
.tab-panel-container .tab.selected {
filter: brightness(130%);
}

/* hovered outer + default tab is brighter than default but not as bright as default + selected */
.tab-panel-container:hover .tab {
filter: brightness(120%);
background-color:var(--background-primary);
}

/* hovered outer hovered default is a bit brighter than hovered outer + default */
.tab-panel-container:hover .tab:hover {
filter: brightness(140%);
}

/* hovered outer + selected is brighter than hovered outer + hovered default and default selected*/
.tab-panel-container:hover .tab.selected {
filter: brightness(160%);
background-color:var(--background-primary);
}

/* hovered out hovered selected is brightest*/
.tab-panel-container:hover  .tab.selected:hover {
filter: brightness(180%);
}
/* end hover on tab */




```
